### PR TITLE
Refactoring for easier maintenance

### PR DESCRIPTION
**Pull request by partoftheworlD**
It is desirable to cover the code with tests, which, unfortunately, I did not have time to do yet.

### CODE REVIEW

**Comment by GMPranav** [comment]
Very nice work! I knew my code was garbage, looks a lot more neat now. BTW, I assume the readme needs to be updated?

**Comment by GMPranav** [comment]
I just tested the code, it seems to work fine for small games, but when I tested it for pop1, it took significantly longer time and also returned a LOT of false positives. I assume the longer time is because you checked the status one by one rather than in batches and not sure why the false positives happened.

**Comment by partoftheworlD** [comment]
I think games with a lot of runs can have false positives, because it's some kind of limitation by Youtube Data API, if you look at the traffic info you can see that after 3-4 thousand requests the error rate starts to increase and false positive links are usually always the latest

image

**Comment by GMPranav** [comment]
Another reason why doing the youtube api requests in batches is a good idea, it takes the same quota for single and batch requests, so reducing the number of requests might avoid this

**Pull request merged**
